site_name: Algobook
site_url: https://neegor.github.io/algobook/
site_description: Сайт про всякие алгоритмы.
site_author: Igor Gorschal
repo_url: https://github.com/neegor/algobook
theme:
  name: material
  locale: ru
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.path
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - IoT и сетевые технологии:
      - md/batch_updates.md
      - md/even_tree.md
  - Аналитика данных и базы данных:
      - md/fp_growth.md
      - md/apriori_algorithm.md
      - md/merkle_tree.md
      - md/check_cycle.md
      - md/data_transformations.md
      - md/facade.md
      - md/cqrs.md
      - md/batch_updates.md
      - md/merkle_patricia_trie.md
  - Биотехнологии и медицинская информатика:
      - md/linucb.md
      - md/multidimensional_dp.md
      - md/1ddp.md
  - ГИС и картография:
      - md/jump_point_search.md
  - Графовые модели и социальные сети:
      - md/check_cycle.md
      - md/bidirectional_a_star.md
      - md/even_tree.md
  - Игровая разработка:
      - md/jump_point_search.md
      - md/sac_rnd.md
      - md/deep_q_networks.md
      - md/flyweight.md
      - md/astar.md
      - md/prototype.md
      - md/bidirectional_a_star.md
  - Логистика и управление цепочками:
      - md/jump_point_search.md
      - md/multidimensional_dp.md
      - md/astar.md
      - md/1ddp.md
      - md/bidirectional_a_star.md
  - Машинное обучение и рекомендательные системы:
      - md/fp_growth.md
      - md/automatic_differentiation.md
      - md/apriori_algorithm.md
      - md/linucb.md
      - md/moe.md
      - md/rnd.md
      - md/sac_rnd.md
      - md/deep_q_networks.md
      - md/policy_gradient.md
      - md/data_transformations.md
      - md/thompson_sampling.md
      - md/markov_chain.md
      - md/batch_updates.md
      - md/1ddp.md
  - Научные вычисления и физическое моделирование:
      - md/automatic_differentiation.md
      - md/diophantine_equation.md
  - Обработка естественного языка:
      - md/moe.md
      - md/flyweight.md
      - md/markov_chain.md
      - md/1ddp.md
  - Оптимизация и планирование:
      - md/automatic_differentiation.md
      - md/diophantine_equation.md
      - md/astar.md
      - md/check_cycle.md
      - md/thompson_sampling.md
      - md/batch_updates.md
      - md/merkle_patricia_trie.md
      - md/even_tree.md
  - Паттерны проектирования:
      - md/abstract_factory.md
      - md/decorator.md
      - md/merkle_tree.md
      - md/factory_method.md
      - md/flyweight.md
      - md/singleton.md
      - md/prototype.md
      - md/facade.md
      - md/composite.md
      - md/cqrs.md
      - md/bridge.md
      - md/proxy.md
      - md/builder.md
      - md/adapter.md
  - Робототехника и автономные системы:
      - md/jump_point_search.md
      - md/rnd.md
      - md/sac_rnd.md
      - md/astar.md
      - md/bidirectional_a_star.md
  - Торговля и коммерция:
      - md/fp_growth.md
      - md/apriori_algorithm.md
      - md/linucb.md
      - md/uma.md
      - md/amm.md
      - md/deep_q_networks.md
      - md/policy_gradient.md
      - md/facade.md
      - md/thompson_sampling.md
  - Экономика и финансы:
      - md/uma.md
      - md/amm.md
      - md/equated_monthly_installments.md
      - md/multidimensional_dp.md
      - md/markov_chain.md
      - md/1ddp.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - meta
  - tags
  - search:
      lang: ru
